const products = {
  black_timbs: { name: "BLACK TIMBERLAND BOOTS", price: "$250", image: "/clothing/Carti_-_Arrivals_-_Black_Timbs_2-removebg-preview.png", sizes: ["40","41","42","43","44"], category: "shoes" },
  product4: { name: "RICK OWENS SS26 TEMPLE JUMBOLACE SNEAKERS", price: "$990", image: "/clothing/rick-owen-shoe.png", sizes: ["40","41","42", "43", "44"], category: "shoes" },
  dior_pants: { name: "RICK OWENS BLACK & WHITE GEOBASKET LEATHER SNEAKERS", price: "$990", image: "/clothing/AW20-RICK-OWENS-GEOBASKET-LEATHER-PERFORMA-SNEAKERS-BLACK-WHITE.png", sizes: ["40", "41", "42", "43", "44"], category: "shoes" },
  product5: { name: "RICK OWENS PERFORMA TAPE GEOBASKET SNEAKERS", price: "$650", image: "/clothing/AW20-RICK-OWENS-GEOBASKET-PERFORMA-SNEAKERS-W-BLACK.png", sizes: ["40", "41", "42", "43", "44"], category: "shoes" },
  product6: { name: "BALENCIAGA STRIKERS BOOTS", price: "$1200", image: "/clothing/Balenciaga_strikers.png", sizes: ["40", "41", "42", "43", "44"], category: "shoes" },
  mrc_hoodie: { name: "M+RC NOIR HOODIE SS18", price: "$150", image: "/clothing/M+RC_NOIR-removebg-preview 2.png", sizes: ["S","M","L","XL"], category: "tops" },
  product7: { name: "GIVENCHY MEN'S SWEATSHIRT", price: "$440", image: "/clothing/Givenchy_Men_s_Sweatshirt.png", sizes: ["S","M","L"], category: "tops" },
  product8: { name: "RAF SIMONS CONSUMED RED PENELOPE HOODIE", price: "$2000", image: "/clothing/SS03_Raf_Simons__Consumed__Red_Penelope_Hoodie.png", sizes: ["S","M","L"], category: "tops" },
  product9: { name: "FW23 RICK OWENS MOUNTAIN HOODIE \"BOYS IN BLACK\"", price: "$600", image: "/clothing/Rick_Owens_mountain_Hoodie_Boys_in_Black_FW23.png", sizes: ["S","M","L"], category: "tops" },
  product10: { name: "ED HARDY HOODIE", price: "$69", image: "/clothing/Ed_Hardy_hoodie-removebg-preview.png", sizes: ["S","M","L"], category: "tops" },
  product11: { name: "DIOR HOMME AW07 LUSTER PANTS", price: "$650", image: "/clothing/Dior_07_Luster_Pantss-removebg-preview 2.png", sizes: ["M","L"], category: "pants" },
  product12: { name: "TRUE RELIGION BILLIE SUPER T JEANS", price: "$195", image: "/clothing/True_religion_billy_super_T_jeans.png", sizes: ["S","M","L"], category: "pants" },
  product13: { name: "2022 BALenciaga LOST TAPES DARK WASH FLARE JEANS", price: "$1300", image: "/clothing/2022_Balenciaga_Lost_Tapes_Dark_wash_Flare_jeans.png", sizes: ["M","L"], category: "pants" },
  product14: { name: "MARITHE FRANCOIS GIRBAUD ELASTAN JEANS", price: "$100", image: "/clothing/marithe-francois-girbaud-bla-bomull-elastan-jeans.png", sizes: ["S","M","L"], category: "pants" },
  product15: { name: "LEVI'S 527 SLIM BOOTCUT JEANS", price: "$95", image: "/clothing/Levi's 527 slim bootcut.png", sizes: ["S","M","L"], category: "pants" },
  product16: { name: "ANDERSSON BELL DISTRESSED-EFFECT DENIM JACKET", price: "$275", image: "/clothing/Andersson_Bell_distressed-effect_denim_jacket.png", sizes: ["S","M"], category: "jackets" },
  product17: { name: "AW07 Dior Homme Bondage Bib Collar Aviator Jacket", price: "$950", image: "/clothing/Dior_Homme_-_AW07_BondageBib_Collar_Aviator_Jacket.png", sizes: ["S","M","L"], category: "jackets" },
  product18: { name: "AW19 14TH ADDICTION SHEEP SKIN LEATHER CROSSZIP JACKET", price: "$777", image: "/clothing/Jean_Paul_Gaultier_Black_Velvet_Blood_Drip_Jacket.png", sizes: ["S","M"], category: "jackets" },
  product19: { name: "JEAN PAUL GAULTIER BLACK VELVET BLOOD DRIP JACKET", price: "$700", image: "/clothing/14th_Addiction_AW19_Sheep_Skin_Leather_Crosszip_Jacket.png", sizes: ["S","M"], category: "jackets" },
  product20: { name: "H&M JEAN JACKET", price: "$40", image: "/clothing/H_M_-_Jacket2-removebg-preview.png", sizes: ["S","M","L"], category: "jackets" },
  product21: { name: "SAINT LAURENT FULL-GRAIN LEATHER BELT", price: "$440", image: "/clothing/SAINT_LAURENT_2cm_Full-Grain_Leather_Belt_for_Men.png", sizes: ["80","85","90"], category: "belts" },
  product22: { name: "VERSACE MEDUSA BELT", price: "$500", image: "/clothing/Medusa-black-belt.png", sizes: ["80","85","90"], category: "belts" },
  product23: { name: "RED VALENTINO BELT", price: "$350", image: "/clothing/Mytheresa_-_The_Finest_Edit_in_Luxury.png", sizes: ["80","85","90"], category: "belts" },
  product24: { name: "SCUFFERS ZEBRA PRINT BELT", price: "$50", image: "/clothing/Scuffers_zebra_print_belt.png", sizes: ["80","85","90"], category: "belts" },
  product25: { name: "CEINTURE LEOPARD PRINT BELT", price: "$190", image: "/clothing/Leopard_print_Ceinture_Belt.png", sizes: ["80","85","90"], category: "belts" }
};