const products = {
  black_timbs: { name: "BLACK TIMBERLAND BOOTS", price: "$250", image: "/clothing/Carti_-_Arrivals_-_Black_Timbs_2-removebg-preview.png", sizes: ["40","41","42","43","44"], category: "shoes" },
  product4: { name: "RICK OWENS SS26 TEMPLE JUMBOLACE SNEAKERS", price: "$990", image: "/clothing/rick_owen_shoe2-removebg-preview.png", sizes: ["40","41","42", "43", "44"], category: "shoes" },
  dior_pants: { name: "DIOR HOMME AW07 LUSTER PANTS", price: "$650", image: "/clothing/Dior_07_Luster_Pantss-removebg-preview 2.png", sizes: ["S","M","L"], category: "pants" },
  product5: { name: "PRODUCT 5", price: "$XXX", image: "/clothing/product5.png", sizes: ["S","M","L","XL"], category: "pants" },
  product6: { name: "PRODUCT 6", price: "$XXX", image: "/clothing/product6.png", sizes: ["S","M","L"], category: "jackets" },
  mrc_hoodie: { name: "M+RC NOIR HOODIE SS18", price: "$150", image: "/clothing/M+RC_NOIR-removebg-preview 2.png", sizes: ["S","M","L","XL"], category: "tops" },
  product7: { name: "PRODUCT 7", price: "$XXX", image: "/clothing/product7.png", sizes: ["S","M","L"], category: "tops" },
  product8: { name: "PRODUCT 8", price: "$XXX", image: "/clothing/product8.png", sizes: ["S","M","L","XL"], category: "pants" },
  product9: { name: "PRODUCT 9", price: "$XXX", image: "/clothing/product9.png", sizes: ["S","M","L"], category: "jackets" },
  product10: { name: "PRODUCT 10", price: "$XXX", image: "/clothing/product10.png", sizes: ["S","M","L"], category: "tops" },
  product11: { name: "PRODUCT 11", price: "$XXX", image: "/clothing/product11.png", sizes: ["S","M","L","XL"], category: "pants" },
  product12: { name: "PRODUCT 12", price: "$XXX", image: "/clothing/product12.png", sizes: ["S","M","L"], category: "jackets" },
  product13: { name: "PRODUCT 13", price: "$XXX", image: "/clothing/product13.png", sizes: ["S","M","L"], category: "tops" },
  product14: { name: "PRODUCT 14", price: "$XXX", image: "/clothing/product14.png", sizes: ["S","M","L","XL"], category: "pants" },
  product15: { name: "PRODUCT 15", price: "$XXX", image: "/clothing/product15.png", sizes: ["S","M","L"], category: "jackets" },
  product16: { name: "PRODUCT 16", price: "$XXX", image: "/clothing/product16.png", sizes: ["S","M","L"], category: "tops" },
  product17: { name: "PRODUCT 17", price: "$XXX", image: "/clothing/product17.png", sizes: ["S","M","L","XL"], category: "pants" },
  product18: { name: "PRODUCT 18", price: "$XXX", image: "/clothing/product18.png", sizes: ["S","M","L"], category: "jackets" },
  product19: { name: "PRODUCT 19", price: "$XXX", image: "/clothing/product19.png", sizes: ["S","M","L"], category: "tops" },
  product20: { name: "PRODUCT 20", price: "$XXX", image: "/clothing/product20.png", sizes: ["S","M","L","XL"], category: "pants" },
  product21: { name: "PRODUCT 21", price: "$XXX", image: "/clothing/product21.png", sizes: ["S","M","L"], category: "jackets" },
  product22: { name: "PRODUCT 22", price: "$XXX", image: "/clothing/product22.png", sizes: ["S","M","L"], category: "tops" },
  product23: { name: "PRODUCT 23", price: "$XXX", image: "/clothing/product23.png", sizes: ["S","M","L","XL"], category: "pants" },
  product24: { name: "PRODUCT 24", price: "$XXX", image: "/clothing/product24.png", sizes: ["S","M","L"], category: "jackets" },
  product25: { name: "PRODUCT 25", price: "$XXX", image: "/clothing/product25.png", sizes: ["S","M","L"], category: "tops" }
};